apiVersion: v1
kind: Service
metadata:
  name: svc-mysql-fiap
  namespace: fiap
  labels:
    app: mysql-fiap
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 30001
  selector:
    app: mysql-fiap
