version: "3.8"
services:
  db:
    build: 
      context: ./docker
      dockerfile: DockerfileMariadb
    container_name: mysql-fiap
    restart: always
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MYSQL_DB_NAME}
      - MARIADB_USER=${MYSQL_USER}
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./migrations:/migrations
      - ./docker/mariadb:/var/lib/mysql
    networks:
      - fiap-network  
  api:
    build: 
      context: ./docker
      dockerfile: DockerfileNode
    container_name: node-fiap
    restart: always
    volumes:
      - ./:/home/node/app
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    networks:
      - fiap-network  
volumes:
  mysql-data:

networks:
  fiap-network: 