-- INSERIR CAMPOS NA TABELA CLIENTE

ALTER TABLE `cliente`
ADD COLUMN `email` VARCHAR(255) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci',
ADD COLUMN `celular` CHAR(11) NULL DEFAULT NULL COLLATE 'utf8mb4_general_ci';
