apiVersion: v1
kind: ConfigMap
metadata:
  name: db-configmap
data:
  MYSQL_HOST: svc-mysql-fiap:3306
  MARIADB_ROOT_PASSWORD: segredo
  MYSQL_USER: fiap
  MYSQL_PASSWORD: fiap
  MYSQL_DB_NAME: fiap_db
