apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-fiap-configmap
data:
  MYSQL_HOST: svc-mysql-fiap
  MARIADB_ROOT_PASSWORD: segredo
  MARIADB_USER: fiap
  MARIADB_PASSWORD: fiap
  MARIADB_DATABASE: fiap_db
