apiVersion: v1
kind: Pod
metadata:
  name: node-fiap
  labels:
    app: node-fiap
spec:
  containers:
    - name: node-fiap-container
      image: noobezera/node-fiap:v2
      ports:
        - containerPort: 9001
      envFrom:
        - configMapRef:
            name: db-configmap
