apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-fiap-deployment
spec:
  template:
    metadata:
      name: node-fiap
      labels:
        app: node-fiap
    spec:
      containers:
        - name: node-fiap-container
          image: noobezera/node-fiap:latest
          ports:
            - containerPort: 9001
          envFrom:
            - configMapRef:
                name: node-fiap-configmap
          livenessProbe:
            httpGet:
              path: /cliente
              port: 9001
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /cliente
              port: 9001
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 60
  replicas: 3
  selector:
    matchLabels:
      app: node-fiap
