name: Docker Build & Push with SonarCloud Analysis

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log into Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build Docker image
      run: docker build -t fiappos/node-fiap .

    - name: Push Docker image to Docker Hub
      run: docker push fiappos/node-fiap

  sonarcloud-analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache SonarCloud packages
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: |
          ${{ runner.os }}-sonar

    - name: SonarCloud Scan
      run: |
        docker run --rm \
          -e SONAR_TOKEN="${{ secrets.SONAR_TOKEN }}" \
          -v "${PWD}:/usr/src" \
          -w /usr/src sonarsource/sonar-scanner-cli:latest \
          sonar-scanner

    - name: Publish SonarCloud Quality Gate result
      if: always()
      uses: sonarsource/sonarcloud-github-action@master
      with:
        github-token: ${{ secrets.TOKEN-FIAP }}
